export const SHAPE_MESSAGE_SAMPLES: string[] = [
  'Amanda Carter: The morning light feels surprisingly warm today.',
  'Daniel Brooks: Coffee first, then we can figure everything out.',
  'Olivia Bennett: I think this idea could actually work.',
  'Lucas Morgan: The weather changed faster than expected.',
  'Sophia Turner: Let\'s keep this simple and move forward.',
  'Ethan Parker: Something interesting happened on my way home.',
  'Emma Collins: This song has been stuck in my head.',
  'Noah Mitchell: Maybe tomorrow will be a better day.',
  'Chloe Anderson: I finally finished everything on my list.',
  'Liam Foster: The city looks beautiful after the rain.',
  'Grace Wilson: We should try something completely different.',
  'Henry Cooper: That was definitely not part of the plan.',
  'Mia Richardson: I found something really interesting yesterday.',
  'James Harrison: Everything seems much easier now.',
  'Lily Thompson: The weekend went by incredibly quickly.',
  'Oliver Bennett: I have a pretty good feeling about this.',
  'Emily Walker: Let\'s meet somewhere quiet this evening.',
  'Jack Peterson: Sometimes the simplest solution works best.',
  'Sarah Morrison: I forgot how peaceful this place feels.',
  'William Scott: Tomorrow we can start something new.',
];